---
- name: Ensure SSH key login is enabled
  ansible.builtin.lineinfile:
    path: /host/etc/ssh/sshd_config
    regexp: '^PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
    state: present
    create: yes

- name: Set authorized keys
  ansible.posix.authorized_key:
    user: cowboy
    key: "{{ item }}"
    state: present
  loop:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII4KEBNHcPwnQaGW+gS/SXkEf8+UxKBDtJr9TgBC5qOq wellcaffeinated@CoffeeCake.local
  tags: [ssh_keys]

# Harden SSH: disable password auth
- name: Disable password authentication in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present

# Ensure ChallengeResponseAuthentication is off
- name: Disable ChallengeResponseAuthentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication'
    line: 'ChallengeResponseAuthentication no'
    state: present
  notify: 
    - sshd

# - name: Dummy task to trigger ssh restart
#   ansible.builtin.debug:
#     msg: "Triggering SSH handler"
#   notify: 
#     - sshd
#   changed_when: true