---
- name: Deploy Nomad server configuration
  ansible.builtin.template:
    src: 20-server.hcl.j2
    dest: /etc/nomad.d/20-server.hcl
    owner: nomad
    group: nomad
    mode: '0640'
  notify:
    - restart-nomad
