---
- name: Deploy Nomad server configuration
  ansible.builtin.template:
    src: 20-server.hcl.j2
    dest: /etc/nomad.d/20-server.hcl
    owner: nomad
    group: nomad
    mode: '0640'
  notify:
    - restart-nomad

- name: Create ARA data directory
  ansible.builtin.file:
    path: /nomad/ara
    state: directory
    mode: '0755'
