---
- name: Create any missing directories
  file:
    path: "{{item.path}}"
    state: directory
  with_items: "{{nomad_volumes|default([])}}"
  loop_control:
    label: "{{item.name}}"

- name: Deploy Nomad client configuration
  ansible.builtin.template:
    src: 20-client.hcl.j2
    dest: /etc/nomad.d/20-client.hcl
    owner: nomad
    group: nomad
    mode: '0640'
  notify:
    - restart-nomad
